### ISSUE TITLE
damo damos documentation

### ISSUE THREAD

**Issue by rajagond** [damonitor/damo#15]
```bash
$DAMO_PATH/damo start --ops paddr --damos_access_rate 5 max --damos_sz_region 4K max \
                          --damos_age 5s max --damos_action migrate_hot 0
 ```
Hi, I have a few questions regarding the damo arguments:

Why do we need two separate actions, `migrate_hot` and `migrate_cold`? Can't we merge both into a single argument, `migrate`, since we already require `<numa_node>` as the second argument?
According to the `damo start --help` page, `--damos_access_rate <min> <max>` should be in percent. What does "percent" mean in this context? How is the percentage being calculated?
The `damo start --help` page also mentions that the arguments for `damos_age` should be in microseconds. If I'm passing an argument with the suffix 's', does it interpret it as seconds?
What do damos_sz_region min and max represent?

**Comment by sjp38** [comment]
Hi @rajagond , thank you for the questions.

> Why do we need two separate actions, migrate_hot and migrate_cold? Can't we merge both into a single argument, migrate, since we already require <numa_node> as the second argument?

Each scheme could have [quotas](https://docs.kernel.org/mm/damon/design.html#quotas).  When DAMON finds memory regions that eligible to apply the action more than the quota, DAMON [prioritizes](https://docs.kernel.org/mm/damon/design.html#prioritization) regions and apply higher priority regions up to only the quota.  The prioritization is done based on the access pattern and the characteristic of the action.  In case of `migrate_hot` and `migrate_cold`, regions that accessed more frequently (hot) and rarely (cold) are respectively prioritized.  This is why we have the two separate actions.

> --damos_access_rate <min> <max> should be in percent. What does "percent" mean in this context? How is the percentage being calculated?

It is called [access frequency](https://docs.kernel.org/mm/damon/design.html#access-frequency-monitoring).  DAMON checks if each region is accessed for each of a time interval called `sampling interval` (5ms by default).  If it turns out a region has accessed since last check, it increments a counter for the region.  The counter is reset for each of another time interval called `aggregation interval` (100ms by default).  The "percent" is calculated just before the counter reset, as the value of the counter divided by the possible maximum value of the counter ('aggregation interval' divided by 'sampling interval': `100ms / 5ms = 20` by default).  So, it can be thought of as a probability of if the region has accessed recently.

> damos_age should be in microseconds. If I'm passing an argument with the suffix 's', does it interpret it as seconds?

You're right.  If you pass, say, `2.5s`, it should be translated to 2,500,000 microseconds.

> What do damos_sz_region min and max represent?

It's a part of the DAMOS target access [pattern](https://docs.kernel.org/mm/damon/design.html#target-access-pattern).  If you set those, the scheme's action will be applied to regions of the size in the range.

For example, let's say you get below `damo` execution outputs.

```
$ sudo ./damo start --damos_action pageout --damos_access_rate 0% 0% --damos_age 10s max --damos_sz_region 100M max
$ sudo ./damo show
0   addr [85.541 TiB  , 85.541 TiB ) (57.707 MiB ) access 0 %   age 10.400 s
1   addr [85.541 TiB  , 85.542 TiB ) (413.285 MiB) access 0 %   age 11.400 s
2   addr [127.649 TiB , 127.649 TiB) (57.500 MiB ) access 0 %   age 1.600 s
3   addr [127.649 TiB , 127.649 TiB) (32.500 MiB ) access 0 %   age 500 ms
4   addr [127.649 TiB , 127.649 TiB) (9.535 MiB  ) access 100 % age 300 ms
5   addr [127.649 TiB , 127.649 TiB) (8.000 KiB  ) access 60 %  age 0 ns
6   addr [127.649 TiB , 127.649 TiB) (6.926 MiB  ) access 0 %   age 1 s
7   addr [127.998 TiB , 127.998 TiB) (120.000 KiB) access 0 %   age 11.100 s
8   addr [127.998 TiB , 127.998 TiB) (8.000 KiB  ) access 40 %  age 100 ms
9   addr [127.998 TiB , 127.998 TiB) (4.000 KiB  ) access 0 %   age 11 s
total size: 577.590 MiB
```

Because of `--damos_access_rate` and `--damos_age`, the `pageout` action could be applied to regions `0`, `1`, and `7`.  And due to the `--damos_sz_region`, the action will be applied to only region `1`.

Please let me know if anything is not answered, or still unclear!

**Comment by rajagond** [comment]
Thanks for the explanation!

Yeah, access frequency makes more sense to me. The term access_rate is a bit confusing. Does the % symbol in demos_access_rate make any difference? 

DAMO provides a userspace interface for [DAMON-based tiered memory management for CXL memory](https://lwn.net/Articles/978313/), which was recently integrated into the Linux kernel. What parameters did they use in their experiments? Can we replicate their results with DAMO? We tried reaching out to the authors, but unfortunately, we didn't get a response.

Thanks!

**Comment by sjp38** [comment]
> Does the % symbol in demos_access_rate make any difference?

No, it shouldn't.  For example, `--damos_access_rate 1.5% 50.1%` and `--damos_access_rate 1.5 50.1` should mean same.

> What parameters did they use in their experiments?

I think they are using a [script](https://github.com/skhynix/hmsdk/blob/main/tools/gen_config.py) for generating the parameters.  I think you can get some hints from the code.

> Can we replicate their results with DAMO?

I believe so, but maybe the authors know better.

> We tried reaching out to the authors, but unfortunately, we didn't get a response.

It's strange.  @honggyukim is one of the main authors, and he responds very quickly and nicely in usual.  Maybe some temporal email delivery accidents have happened?

**Comment by honggyukim** [comment]
Hi @rajagond,

It's weired that I haven't received any contact from you.

Anyway, you can use migrate_cold and migrate_hot with HMSDK's policy generator, which can be found at https://github.com/skhynix/hmsdk/wiki/Capacity-Expansion.

The policy can be generated with [gen_cong.py](https://github.com/skhynix/hmsdk/blob/main/tools/gen_config.py) but you can modify our policy if you need. Please have a look and let us know if you have some issues.

Thanks for your interest!

**Comment by rajagond** [comment]
Got it, Thanks! One of my teammates sent an email a while ago. Yeah, it might be possible that we sent it to a temporary email address. Sorry about that.

On the same topic (i.e., DAMON-CXL), I have a few more doubts. How does this solution look in an online setting (i.e., in real time)? Do we need to do some kind of adaptive configuration? The results on YCSB are quite impressive, though.

Thanks!

**Comment by honggyukim** [comment]
> Got it, Thanks! One of my teammates sent an email a while ago. Yeah, it might be possible that we sent it to a temporary email address. Sorry about that.

It's okay. I would like to get questions at https://github.com/skhynix/hmsdk/issues, but you can also send me an email if you need.

> On the same topic (i.e., DAMON-CXL), I have a few more doubts. How does this solution look in an online setting (i.e., in real time)?

What do you mean by online setting? Do you mean changing DAMON configuration while it's running? If so, HMSDK doesn't ask users to change configs while it's running while it can be turned on and off.

> Do we need to do some kind of adaptive configuration?

We would like to use feedback driven autotuning feature later but it's not ready yet.

> The results on YCSB are quite impressive, though.

Thanks. The basic performance gain comes from promoting hot data to fast tiers while cold data is getting demoted to slow tiers. The performance gain of redis/YCSB comes from placing hot data of redis goes to fast DRAM under memory pressured environment.

**Comment by rajagond** [comment]
By "online setting," I meant dealing with real-time, unknown workloads. For simulated workloads, we can profile them offline, such as with YCSB workloads, and choose the best configurations. However, when handling unknown workloads in real time, we can't profile them beforehand to determine the optimal configurations.

Also, is there a way to get statistics on page migration using DAMO, such as the number of pages migrated from node #0 to node #1 or vice-versa?

**Comment by rajagond** [comment]
> Hi @rajagond,
> 
> It's weired that I haven't received any contact from you.
> 
> Anyway, you can use migrate_cold and migrate_hot with HMSDK's policy generator, which can be found at https://github.com/skhynix/hmsdk/wiki/Capacity-Expansion.
> 
> The policy can be generated with [gen_cong.py](https://github.com/skhynix/hmsdk/blob/main/tools/gen_config.py) but you can modify our policy if you need. Please have a look and let us know if you have some issues.
> 
> Thanks for your interest!

Hi @honggyukim ,

I looked at the [workload](https://github.com/skhynix/hmsdk/wiki/Capacity-Expansion#2-workloads) section, but I still couldn't find the exact YCSB workload you used in your experiments. There are several YCSB workloads, such as workloada, workloadb, workloadc, etc. Which workload have you used in your experiment? If possible, could you please share the Redis run/load properties files?

Thanks!

**Comment by honggyukim** [comment]
> By "online setting," I meant dealing with real-time, unknown workloads. For simulated workloads, we can profile them offline, such as with YCSB workloads, and choose the best configurations. However, when handling unknown workloads in real time, we can't profile them beforehand to determine the optimal configurations.

Yeah, it'd be much better to make it work with adjusted configuration, but our redis result doesn't use it. I just found reasonable configuration set as of now and have a plan to apply auto tuning for at least quota setup.

**Comment by honggyukim** [comment]
> I looked at the [workload](https://github.com/skhynix/hmsdk/wiki/Capacity-Expansion#2-workloads) section, but I still couldn't find the exact YCSB workload you used in your experiments. There are several YCSB workloads, such as workloada, workloadb, workloadc, etc. Which workload have you used in your experiment? If possible, could you please share the Redis run/load properties files?

And this is more related to hmsdk question but I will explain anyway.

The default YCSB workload requires small size of memory so it wasn't suitable to evaluate our migration schemes so we made the workload setup as follows.
```diff
@@ -14,15 +14,15 @@
 # LICENSE file.

 # Yahoo! Cloud System Benchmark
-# Workload C: Read only
+# Workload C: Read only - increase record from 1000 to 30000000, operation from 1000 to 5000000
 #   Application example: user profile cache, where profiles are constructed elsewhere (e.g., Hadoop)
 #
 #   Read/update ratio: 100/0
 #   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
 #   Request distribution: zipfian

-recordcount=1000
-operationcount=1000
+recordcount=30000000
+operationcount=5000000
 workload=site.ycsb.workloads.CoreWorkload

 readallfields=true
```
The `recordcount` increases memory consumption and `operationcount` increases execution time. It consums 85GB(52GB for anon and 33GB for file cache) and each execution time is about 1 minute. For better evaluation, we executed each ycsb run 50 times and got average.

Except for the above workload file, I explained the details at my cover letter at https://lore.kernel.org/damon/20240614030010.751-1-honggyu.kim@sk.com.

I hope this is helpful to you.

**Comment by sjp38** [comment]
> And this is more related to hmsdk question

Indeed.  Please consider continuing the discussion on the HKSDK issues (https://github.com/skhynix/hmsdk/issues), as suggested in the previous [comment](https://github.com/damonitor/damo/issues/15#issuecomment-2325477223).

I hope my poor communication skill is not making you get my points wrong.  Any traffic is helpful for humble open-source projects like DAMON.  I'm very happy at you continuing discussion here.  However I believe the HMSDK issues page is the more effective place for the discussion of this topic, and it will also benefit DAMON project in the long term.

I will do my best to help with the follow-up discussion regardless of the place.  That's what I happily committed to do.  Just don't forget to properly mention me, or remind me if I don't respond longer than you expected, for any topics that you want my opinions on.

**Comment by rajagond** [comment]
Thanks @honggyukim !

Sure, @sjp38, I would continue the discussion on hmsdk page. Since it was closely related to the above discussion, I thought it would be better to put here for future reference. Thanks!
