### ISSUE TITLE
provide a way to turn on/off damon from userspace

### ISSUE THREAD

**Issue by sjp38** [damonitor/damo#2]
This is for continuing the discussion from https://github.com/awslabs/damo/issues/47

**Comment by sjp38** [comment]
We agree implementing the requested feature could be useful, but not clearly aligned about the benefit it provides.  Currently this is a low priority task.  Once a clear use case is given, we could prioritize this.

**Comment by honggyukim** [comment]
I agree this is not an urgent task so I don't mind closing this if you don't want to keep this issue.
