### ISSUE TITLE
[RFC] support damo update command

### ISSUE THREAD

**Issue by sj-aws** [damonitor/damo#7]
For continuing discussion from https://github.com/awslabs/damo/issues/72

**Comment by sjp38** [comment]
According to the comment on the original issue (https://github.com/awslabs/damo/issues/72#issuecomment-1784145086), there is no action item from my side.  I'm waiting for test results from @honggyukim .  @honggyukim , please take your time for testing and let me know if there is anything I can further help.

**Comment by honggyukim** [comment]
Thanks for the remind. I will try to use `damo tune` as you mentioned at https://github.com/awslabs/damo/issues/72#issuecomment-1664244640. So we can close this issue.

**Comment by sjp38** [comment]
> I don't have a permission to close this issue so will leave it now.

No problem, I'm closing now.  Please do same for similar cases :)
